// ─────────────────────────────────────────────────────────────────────────────
// ART HUNTER — ARTISTS, GALLERIES & VENUES
// ─────────────────────────────────────────────────────────────────────────────

export const ARTISTS = [

  // ── BLUE CHIP ────────────────────────────────────────────────────────────
  { id:1,  rank:1,  name:"Andy Warhol", medium:"Prints & Editions", era:"1960s–80s", category:"Blue Chip", tier:"blue chip", value:"$2,000–$500,000", findable:true, signal:"very hot", description:"The safest anchor in the market. Silkscreen prints — Marilyn, Mao, Campbell's, flowers — are the hunt target. Unsigned or off-condition pieces at estate sales regularly surface at 5–10% of authenticated market value. A $18M Warhol sold at Art Basel Miami Beach in December 2025. For hunters: look for trial proofs and unsigned editions." },
  { id:2,  rank:2,  name:"David Hockney", medium:"Prints, Drawings, Paintings", era:"1960s–present", category:"Blue Chip", tier:"blue chip", value:"$5,000–$100,000", findable:true, signal:"stable", description:"One of the few living artists at true blue-chip status. Prints have delivered 8.9% average annual return over 20 years. Limited edition lithographs from the 1970s–80s are the sweet spot for hunters — still findable at reasonable prices. Look for the Swimming Pool series and Portrait of an Artist editions." },
  { id:3,  rank:3,  name:"Yayoi Kusama", medium:"Prints, Paintings, Sculpture", era:"1960s–present", category:"Blue Chip", tier:"blue chip", value:"$8,000–$200,000", findable:false, signal:"stable", description:"Surrealism tailwinds are strong in 2026 and Kusama benefits directly. Her prints are among the most actively traded in the world. The dot motif makes authentication relatively straightforward — and fakes are extremely common. Your UV light and loupe are essential here. Look for the Infinity Nets and pumpkin series editions." },
  { id:4,  rank:4,  name:"Banksy", medium:"Prints, Stencil Works", era:"1990s–present", category:"Blue Chip", tier:"blue chip", value:"$5,000–$14,000,000", findable:true, signal:"stable", description:"The anonymous street artist whose prints are among the most actively traded in the contemporary market. Girl with Balloon, Sunflowers from Petrol Station. Authenticated prints through Pest Control (his authentication body) are the only ones worth acquiring. Fakes are rampant — never buy without Pest Control certificate." },
  { id:5,  rank:5,  name:"KAWS", medium:"Prints, Sculpture, Paintings", era:"2000s–present", category:"Blue Chip", tier:"blue chip", value:"$3,000–$50,000", findable:true, signal:"very hot", description:"Brian Donnelly's Companion figures and print editions are among the most widely collected in the world. Strong secondary market with deep liquidity. Entering 2026 with increasing visibility and serious collector engagement. Edition prints still available at accessible price points relative to paintings." },
  { id:6,  rank:6,  name:"Jean-Michel Basquiat", medium:"Paintings, Works on Paper", era:"1980s", category:"Blue Chip", tier:"blue chip", value:"$50,000–$110,000,000", findable:false, signal:"stable", description:"The crown jewel of 1980s American art. Works on paper occasionally surface at regional auctions misattributed or without full provenance. Any Basquiat requires extreme authentication diligence — fakes are among the most sophisticated in the market. Provenance research is non-negotiable." },
  { id:7,  rank:7,  name:"Harland Miller", medium:"Paintings, Prints", era:"2000s–present", category:"Blue Chip", tier:"blue chip", value:"$20,000–$200,000", findable:true, signal:"act now", description:"His Penguin book cover paintings are among the most culturally legible works in contemporary art. He's ending his Penguin-format editions — supply is contracting while institutional attention is growing via major museum exhibitions. The window to acquire at current prices is closing. Edition prints starting around £20K." },

  // ── MID-CAREER ────────────────────────────────────────────────────────────
  { id:8,  rank:8,  name:"Jadé Fadojutimi", medium:"Paintings", era:"2010s–present", category:"Mid-Career", tier:"mid-career", value:"$80,000–$1,800,000", findable:false, signal:"rising fast", description:"British-Nigerian painter born 1993. In the Tate collection. A 2023 Christie's diptych hit nearly $1.8M. Lyrical color-rich abstractions that are the anti-AI antidote collectors are hunting: maximum evidence of the human hand. Still producing — ceiling unknown. Female artist premium still closing. One of the clearest buys in the market." },
  { id:9,  rank:9,  name:"Issy Wood", medium:"Paintings", era:"2010s–present", category:"Mid-Career", tier:"mid-career", value:"$15,000–$150,000", findable:false, signal:"act now", description:"British painter born 1993. Represented by Gagosian — one of the clearest institutional validation signals available. Strong secondary market results. Her surrealist realism and the surrealism wave of 2026 are perfectly aligned. Smaller works still accessible before gallery prices fully reflect the market. Move before the next solo show." },
  { id:10, rank:10, name:"Loie Hollowell", medium:"Paintings", era:"2010s–present", category:"Mid-Career", tier:"mid-career", value:"$8,000–$764,000", findable:false, signal:"proven", description:"American painter born 1983. Prices up 1,200% since her 2016 debut show. Average auction sale now $764K — 152% over estimate. The trajectory is exceptionally steep. Earlier works that surface privately or at regional auctions are still findable at a fraction of primary market price. Geometric abstraction with biological undertones." },
  { id:11, rank:11, name:"Lucas Arruda", medium:"Paintings", era:"2010s–present", category:"Mid-Career", tier:"mid-career", value:"$30,000–$278,000", findable:false, signal:"rising", description:"Brazilian painter born 1983. In the Getty and Rubell Museum. Average auction sale $278K — 110% over estimate. Semi-abstract landscapes — hazy beaches, dense forests — with an extraordinary cinematic quality. A genuinely beautiful body of work that rewards sustained attention. Cross London, New York, and Paris exhibitions establishing international market." },
  { id:12, rank:12, name:"Tunji Adeniyi-Jones", medium:"Paintings", era:"2010s–present", category:"Mid-Career", tier:"mid-career", value:"$15,000–$100,000", findable:false, signal:"rising", description:"British-Nigerian painter. White Cube shows in New York and Seoul. Auction prices now exceeding $100K — the market is actively forming. Richly colored figurative work in the same cultural conversation as Fadojutimi. Acquire before the market fully matures. Strong institutional trajectory and clear international gallery support." },
  { id:13, rank:13, name:"Flora Yukhnovich", medium:"Paintings", era:"2010s–present", category:"Mid-Career", tier:"mid-career", value:"$20,000–$3,000,000", findable:false, signal:"very hot", description:"British painter. Rococo-infused abstraction with extraordinarily strong auction results. Recent works at auction achieving multiples above estimate. The lush, historical reference point combined with contemporary sensibility has attracted major museum and collector attention. Female artist in an undervalued cohort still closing the gap." },
  { id:14, rank:14, name:"Salman Toor", medium:"Paintings", era:"2010s–present", category:"Mid-Career", tier:"mid-career", value:"$30,000–$500,000", findable:false, signal:"rising", description:"Pakistani-American figurative painter. Intimate narrative-driven works increasingly acquired by museums and private institutional collections. Small-scale paintings of queer life in domestic and social settings. Whitney Museum solo exhibition. A rare artist whose market is growing in direct proportion to critical and institutional support." },
  { id:15, rank:15, name:"Shara Hughes", medium:"Paintings", era:"2010s–present", category:"Mid-Career", tier:"mid-career", value:"$40,000–$800,000", findable:false, signal:"stable", description:"American painter. Vivid, expressive landscapes that occupy a space between real and imagined terrain. Steady sales growth with consistent institutional interest and major gallery representation. A reliable market with clear upward trajectory. One of the strongest American painters working in landscape idiom today." },

  // ── EMERGING ──────────────────────────────────────────────────────────────
  { id:16, rank:16, name:"Mulgil Kim", medium:"Paintings", era:"2020s", category:"Emerging", tier:"emerging", value:"$3,000–$20,000", findable:true, signal:"early stage", description:"South Korean artist. Debut solo show at Maddox Gallery, summer 2026. Serene, nature-inspired surrealist paintings developed through a global Art Road journey. Timed perfectly against the 2026 surrealism wave — Christie's Surreal sale hit £48M in 2025 with a 96% sell-through rate. Earliest acquisition window open right now." },
  { id:17, rank:17, name:"Zhou Song", medium:"Paintings", era:"2020s", category:"Emerging", tier:"emerging", value:"$5,000–$30,000", findable:true, signal:"rising", description:"Entering 2026 with increasing visibility and serious collector engagement. Clear artistic language and coherent body of work — the two qualities collectors are paying most attention to in 2026. Institutional attention building. One to watch across the year as exhibition history develops." },
  { id:18, rank:18, name:"Celine Ali", medium:"Mixed Media", era:"2020s", category:"Emerging", tier:"emerging", value:"$2,000–$15,000", findable:true, signal:"watch", description:"Emerging artist with a distinctive practice attracting gallery and critical attention. Works reward sustained viewing — the quality collectors are specifically seeking in 2026 over novelty or quick visibility. Coherent authorship across mediums. Early acquisition before institutional validation sets prices." },
  { id:19, rank:19, name:"Qualeasha Wood", medium:"Woven Textiles", era:"2020s", category:"Emerging", tier:"emerging", value:"$10,000–$80,000", findable:false, signal:"watch", description:"Works in woven fabric — a medium that positions her directly in the handcraft wave of 2026 where collectors are actively seeking work that AI cannot replicate. No cheap editions available. Original woven works only. Keep on radar as investment opportunities come to market. Museum curators are watching." },
  { id:20, rank:20, name:"Avery Singer", medium:"Paintings", era:"2010s–present", category:"Emerging", tier:"emerging", value:"$50,000–$4,100,000", findable:false, signal:"very hot", description:"Set the record for highest auction price by a female ultra-contemporary artist in 2023 with Untitled (2018) at $4.1M. Paintings use digital tools to create eerily flat, computer-rendered scenes. The market has formed decisively. Earlier works are the target — post-record prices reflect a matured market." },

  // ── PRINTS & EDITIONS HUNT ────────────────────────────────────────────────
  { id:21, rank:21, name:"Roy Lichtenstein", medium:"Prints & Editions", era:"1960s–90s", category:"Prints Hunt", tier:"blue chip", value:"$3,000–$50,000", findable:true, signal:"stable", description:"The strongest hunt category in 2026 is prints, and Lichtenstein is the prime target. Screenprints and lithographs from the 1960s–80s are undervalued relative to paintings. Ben-Day dot patterns are highly datable under a loupe. Estate sales and regional auctions regularly surface misidentified Lichtenstein prints." },
  { id:22, rank:22, name:"Cindy Sherman", medium:"Photography", era:"1970s–present", category:"Photography", tier:"mid-career", value:"$10,000–$3,900,000", findable:false, signal:"stable", description:"The definitive artist of photographic self-staging. Vintage prints from the Untitled Film Stills series (1977–80) are the holy grail of contemporary photography collecting. Later editions are more accessible. Authentication via gallery records is essential — provenance trail from Metro Pictures or Sprüth Magers." },
  { id:23, rank:23, name:"Wolfgang Tillmans", medium:"Photography", era:"1990s–present", category:"Photography", tier:"mid-career", value:"$5,000–$300,000", findable:false, signal:"stable", description:"Turner Prize winner. One of the most important photographers working. Large-scale prints mounted directly to wall without frames are signature. Smaller works and editions are accessible entry points. A complete body of work that spans intimacy and abstraction — photographic prints as fine art objects." },
  { id:24, rank:24, name:"Nan Goldin", medium:"Photography", era:"1970s–present", category:"Photography", tier:"blue chip", value:"$8,000–$200,000", findable:false, signal:"rising", description:"The Ballad of Sexual Dependency (1986) is the cornerstone of documentary photography as fine art. Cibachrome prints from the 1980s–90s are increasingly institutional-grade. P.A.I.N. activism has elevated her cultural status significantly. The estate market will be transformative. Collect now before posthumous premium." },
  { id:25, rank:25, name:"Mickalene Thomas", medium:"Paintings, Photography", era:"2000s–present", category:"Mid-Career", tier:"mid-career", value:"$20,000–$600,000", findable:false, signal:"rising", description:"Leading voice in contemporary portraiture. Rhinestone-encrusted paintings of Black women drawing on art history, pop culture, and domestic space. Multifaceted market across paintings, photography, and collage. Strong museum presence and collector base. The female artist arbitrage window applies here at full force." },
];

export const ART_CATEGORIES = ["All", "Blue Chip", "Mid-Career", "Emerging", "Prints Hunt", "Photography"];
export const ART_TIERS = ["All", "blue chip", "mid-career", "emerging"];
export const ART_SIGNALS = ["All", "very hot", "act now", "rising fast", "rising", "proven", "stable", "early stage", "watch"];

// ─────────────────────────────────────────────────────────────────────────────
// ART GALLERIES & VENUES
// ─────────────────────────────────────────────────────────────────────────────
export const GALLERIES = [
  // New York
  { id:1, name:"Gagosian", city:"New York, NY", area:"newyork", specialty:"Blue chip contemporary & modern", address:"980 Madison Ave, New York, NY 10075", hours:"Tue-Sat 10am-6pm", website:"https://gagosian.com", rating:4.9, notes:"The most powerful gallery in the world. Represents Issy Wood, Damien Hirst, Jeff Koons among many. Multiple locations globally. Building a relationship here opens doors across the entire blue-chip market." },
  { id:2, name:"David Zwirner", city:"New York, NY", area:"newyork", specialty:"Contemporary painting & photography", address:"525 W 19th St, New York, NY 10011", hours:"Tue-Sat 10am-6pm", website:"https://davidzwirner.com", rating:4.9, notes:"Represents some of the most important living artists including Wolfgang Tillmans and Neo Rauch. Strong secondary market program. Gallery known for building long collector relationships." },
  { id:3, name:"Hauser & Wirth", city:"New York, NY", area:"newyork", specialty:"Modern & contemporary across all media", address:"542 W 22nd St, New York, NY 10011", hours:"Tue-Sat 11am-6pm", website:"https://hauserwirth.com", rating:4.8, notes:"Global mega-gallery with extraordinary depth. Strong program across painting, sculpture, and photography. Somerset, Menorca, and LA locations. Known for long-term artist stewardship." },
  { id:4, name:"Metro Pictures", city:"New York, NY", area:"newyork", specialty:"Conceptual & photographic", address:"519 W 24th St, New York, NY 10011", hours:"Tue-Sat 10am-6pm", website:"https://metropicturesgallery.com", rating:4.7, notes:"Historic Chelsea gallery known for Cindy Sherman, Robert Longo. The provenance trail for major photographic works often leads here. An important relationship for photography collectors." },
  { id:5, name:"Marian Goodman", city:"New York, NY", area:"newyork", specialty:"International contemporary", address:"24 W 57th St, New York, NY 10019", hours:"Mon-Sat 10am-6pm", website:"https://mariangoodman.com", rating:4.8, notes:"Represents Gerhard Richter, Steve McQueen, William Kentridge. Strong European artist roster. Known for critical depth and serious collector relationships. Paris and London locations." },
  { id:6, name:"White Cube", city:"New York, NY", area:"newyork", specialty:"Contemporary British & international", address:"1002 Madison Ave, New York, NY 10075", hours:"Tue-Sat 10am-6pm", website:"https://whitecube.com", rating:4.8, notes:"Represents Tunji Adeniyi-Jones, Damien Hirst, Tracey Emin. The gallery that built the YBA market. New York location opened recently. London, Hong Kong, Paris, and Seoul locations." },
  { id:7, name:"Pace Gallery", city:"New York, NY", area:"newyork", specialty:"Modern & contemporary", address:"540 W 25th St, New York, NY 10001", hours:"Tue-Sat 10am-6pm", website:"https://pacegallery.com", rating:4.7, notes:"One of the oldest major contemporary galleries. Strong modern art depth including Rothko, Calder estates. Important for collectors seeking museum-quality historical works." },
  { id:8, name:"NADA Art Fair", city:"New York, NY", area:"newyork", specialty:"Emerging & mid-career", address:"Various NYC venues", hours:"Annual — May", website:"https://newartdealers.org", rating:4.6, notes:"The New Art Dealers Alliance fair is the single best place to find pre-gallery-represented artists. Smaller galleries, lower prices, higher risk and reward. Attend every year without exception." },

  // Los Angeles
  { id:9,  name:"Blum & Poe", city:"Los Angeles, CA", area:"losangeles", specialty:"International contemporary, strong Japanese", address:"2727 S La Cienega Blvd, Los Angeles, CA 90034", hours:"Tue-Sat 10am-6pm", website:"https://blumandpoe.com", rating:4.8, notes:"One of the most important galleries for Japanese contemporary art in America. Strong pipeline of emerging international artists. LA, New York, and Tokyo locations." },
  { id:10, name:"Regen Projects", city:"Los Angeles, CA", area:"losangeles", specialty:"Contemporary American", address:"6750 Santa Monica Blvd, Los Angeles, CA 90038", hours:"Tue-Sat 10am-6pm", website:"https://regenprojects.com", rating:4.8, notes:"Represents Wolfgang Tillmans, Catherine Opie, Laurie Simmons. One of the most critically respected galleries in LA. Strong relationship with museum curators." },
  { id:11, name:"Sprüth Magers", city:"Los Angeles, CA", area:"losangeles", specialty:"Conceptual & photographic", address:"5900 Wilshire Blvd, Los Angeles, CA 90036", hours:"Tue-Sat 10am-6pm", website:"https://spruethmagers.com", rating:4.8, notes:"Represents Cindy Sherman, Barbara Kruger, Andreas Gursky. Critical provenance gallery for photography and conceptual work. Berlin, London, and New York locations." },
  { id:12, name:"Karma", city:"Los Angeles, CA", area:"losangeles", specialty:"Emerging & mid-career painting", address:"Multiple LA locations", hours:"Tue-Sat 11am-6pm", website:"https://karmakarma.org", rating:4.7, notes:"One of the most active galleries for emerging painters. New York and LA locations. Known for introducing artists who go on to major representation. A key stop for pre-gallery scouting." },

  // London
  { id:13, name:"Sadie Coles HQ", city:"London, UK", area:"london", specialty:"Contemporary British & international", address:"62 Kingly St, London W1B 5QN", hours:"Mon-Sat 11am-6pm", website:"https://sadiecoles.com", rating:4.8, notes:"Represents Sarah Lucas, John Currin, Laura Owens. One of the most important London galleries for contemporary work. Strong secondary market program." },
  { id:14, name:"Maddox Gallery", city:"London, UK", area:"london", specialty:"Blue chip & emerging contemporary", address:"9 Maddox St, London W1S 2QE", hours:"Mon-Sat 10am-6pm", website:"https://maddoxgallery.com", rating:4.6, notes:"Represents Banksy (secondary market), Harland Miller, and Mulgil Kim (debut solo 2026). Strong commercial program with accessible entry-level works. Gstaad location also." },
  { id:15, name:"Frith Street Gallery", city:"London, UK", area:"london", specialty:"Photography & contemporary", address:"17-18 Golden Square, London W1F 9JJ", hours:"Tue-Fri 11am-6pm, Sat 11am-5pm", website:"https://frithstreetgallery.com", rating:4.7, notes:"Represents Nan Goldin, Cornelia Parker. One of the most respected mid-size London galleries. Strong photography program and serious collector relationships." },
  { id:16, name:"Maureen Paley", city:"London, UK", area:"london", specialty:"British contemporary", address:"21 Herald St, London E2 6JT", hours:"Wed-Sun 11am-6pm", website:"https://maureenpaley.com", rating:4.8, notes:"East London gallery known for developing British and international artists over long careers. Represents Wolfgang Tillmans, Gillian Wearing, Rebecca Warren. A gallery that builds artists seriously." },

  // Paris
  { id:17, name:"Galerie Chantal Crousel", city:"Paris, France", area:"paris", specialty:"International contemporary", address:"10 Rue Charlot, 75003 Paris", hours:"Tue-Sat 11am-7pm", website:"https://crousel.com", rating:4.7, notes:"One of the most serious Paris galleries for international contemporary art. Strong artist development program. Works with major names and important emerging figures across the spectrum." },
  { id:18, name:"Air de Paris", city:"Paris, France", area:"paris", specialty:"Conceptual & contemporary French", address:"32 Rue Louise Weiss, 75013 Paris", hours:"Tue-Sat 2pm-7pm", website:"https://airdeparis.com", rating:4.6, notes:"Pioneer of the 13th arrondissement gallery scene. Serious conceptual program with strong French and international roster. An important relationship for collectors entering the Paris market." },

  // Berlin
  { id:19, name:"Galerie Buchholz", city:"Berlin, Germany", area:"berlin", specialty:"Conceptual & photography", address:"Fasanenstrasse 30, 10719 Berlin", hours:"Tue-Sat 11am-6pm", website:"https://galeriebuchholz.de", rating:4.7, notes:"Cologne and New York locations also. Critical gallery for conceptual work and photography. Represents important estates and living artists. A serious relationship for serious collectors." },
  { id:20, name:"König Galerie", city:"Berlin, Germany", area:"berlin", specialty:"Contemporary across all media", address:"St. Agnes Kirche, Alexandrinenstr. 118, 10969 Berlin", hours:"Tue-Sat 11am-6pm", website:"https://koeniggalerie.com", rating:4.7, notes:"Based in a former brutalist church. Strong emerging and mid-career program. One of the most architecturally dramatic gallery spaces in the world. Strong London satellite." },

  // Estate Sales & Auction Houses
  { id:21, name:"Christie's", city:"New York, NY", area:"auction", specialty:"All categories — major auction house", address:"20 Rockefeller Plaza, New York, NY 10020", hours:"Mon-Fri 9:30am-5pm", website:"https://christies.com", rating:4.9, notes:"One of the two dominant auction houses. Strong old masters, Impressionist, and contemporary programs. The 'Art of the Surreal' Evening Sale hit £48M in 2025. Online bidding available. Important for tracking market prices." },
  { id:22, name:"Sotheby's", city:"New York, NY", area:"auction", specialty:"All categories — major auction house", address:"1334 York Ave, New York, NY 10021", hours:"Mon-Fri 9am-5pm", website:"https://sothebys.com", rating:4.9, notes:"The other dominant global auction house. Growing Middle East presence with Riyadh and Abu Dhabi auctions. Strong photography program. Monitor their online estimates vs. hammer prices for market intelligence." },
  { id:23, name:"Phillips", city:"New York, NY", area:"auction", specialty:"20th century & contemporary", address:"432 Park Ave, New York, NY 10022", hours:"Mon-Fri 10am-6pm", website:"https://phillips.com", rating:4.7, notes:"The third major auction house, focused on 20th-century and contemporary. Often more accessible price estimates than Christie's or Sotheby's. Strong photography and design programs. London location also." },
  { id:24, name:"Bonhams", city:"New York, NY", area:"auction", specialty:"Specialist categories", address:"580 Madison Ave, New York, NY 10022", hours:"Mon-Fri 9am-5pm", website:"https://bonhams.com", rating:4.5, notes:"Strong specialist auction programs including photographs, prints, and decorative arts. Regional offices globally. Often better value for hunters than the top two houses. Worth monitoring for overlooked lots." },
  { id:25, name:"Swann Auction Galleries", city:"New York, NY", area:"auction", specialty:"Works on paper, photographs, prints", address:"104 E 25th St, New York, NY 10010", hours:"Mon-Fri 10am-5pm", website:"https://swanngalleries.com", rating:4.6, notes:"Specialist auction house focused on works on paper, photographs, and prints — exactly the categories with the highest hunt upside in 2026. Lower estimates, genuine discoveries possible. Attend their photography and prints auctions specifically." },
];

export const GALLERY_AREAS = [
  { key:"all",        label:"ALL" },
  { key:"newyork",    label:"NEW YORK" },
  { key:"losangeles", label:"LOS ANGELES" },
  { key:"london",     label:"LONDON" },
  { key:"paris",      label:"PARIS" },
  { key:"berlin",     label:"BERLIN" },
  { key:"auction",    label:"AUCTION" },
];
